openapi: 3.0.1
info:
  title: Oink Account Management API
  version: 2.1.0
servers:
  - url: https://localhost:7071/api
paths:
  /accounts:
    post:
      tags:
        - fund-mgmt
        - financial-account-mgmt
      operationId: RequestFinancialAccountCreation
      requestBody:
        description: Account information needed to create an account reference in the Oink system.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createNewFinancialAccountRequest'
        required: true
      responses:
        '201':
          description: Financial Account creation requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
        '401':
          description: Access token is missing or invalid
          x-ms-summary: Access token is missing or invalid
        '403':
          description: Access token does not have required scopes
          x-ms-summary: Access token does not have required scopes
        '409':
          description: Financial Account creation request already exists
          x-ms-summary: Financial Account creation account exists
      security:
        - Bearer: [ ]
  '/accounts/{accountId}':
    get:
      tags:
        - financial-account-mgmt
      operationId: GetFinancialAccountByAccountId
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Financial Account found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
        '401':
          description: Access token is missing or invalid
          x-ms-summary: Access token is missing or invalid
        '403':
          description: Access token does not have required scopes
          x-ms-summary: Access token does not have required scopes
        '404':
          description: Financial Account not found
          x-ms-summary: Financial Account not found
      security:
        - Bearer: [ ]
  '/accounts/{accountId}/balances':
    get:
      tags:
        - financial-account-mgmt
      operationId: GetFinancialAccountBalancesByAccountId
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Financial Account found
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Access token is missing or invalid
          x-ms-summary: Access token is missing or invalid
        '403':
          description: Access token does not have required scopes
          x-ms-summary: Access token does not have required scopes
        '404':
          description: Financial Account not found
          x-ms-summary: Financial Account not found
      security:
        - Bearer: [ ]
  '/accounts/{accountId}/payments':
    get:
      tags:
        - financial-account-mgmt
      operationId: GetAccountPaymentsByAccountId
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Financial Account found
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Access token is missing or invalid
          x-ms-summary: Access token is missing or invalid
        '403':
          description: Access token does not have required scopes
          x-ms-summary: Access token does not have required scopes
        '404':
          description: Financial Account not found
          x-ms-summary: Financial Account not found
      security:
        - Bearer: [ ]
components:
  schemas:
    account:
      type: object
      properties:
        accountName:
          type: string
        alias:
          type: string
        classification:
          $ref: '#/components/schemas/accountClassification'
        status:
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
          type: integer
          format: int32
          default: 0
        isActive:
          type: boolean
        routingNumber:
          type: string
        accountNumber:
          type: string
        asset:
          $ref: '#/components/schemas/accountAsset'
        accountIssuerId:
          type: string
          format: uuid
        accountManagers:
          type: array
          items:
            $ref: '#/components/schemas/accountManager'
        balance:
          type: integer
          format: int64
        hold:
          type: integer
          format: int64
        available:
          type: integer
          format: int64
        createdOn:
          type: string
          format: date-time
        annotations:
          type: object
          additionalProperties:
            type: string
        version:
          type: integer
          format: int32
        domainEvents:
          type: array
          items:
            $ref: '#/components/schemas/iDomainEvent'
        id:
          type: string
          format: uuid
    accountAsset:
      type: object
      properties:
        name:
          type: string
        symbol:
          type: string
        id:
          type: string
          format: uuid
    accountClassification:
      type: object
      properties:
        productOwnerIdentifier:
          type: string
          format: uuid
        accountClass:
          enum:
            - 0
            - 1
            - 2
            - 3
          type: integer
          format: int32
          default: 0
        name:
          type: string
        value:
          type: string
    accountManager:
      type: object
      properties:
        name:
          type: string
        id:
          type: string
          format: uuid
    createNewFinancialAccountRequest:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
        accountName:
          type: string
        accountClassIdentifier:
          type: string
        alias:
          type: string
        assetId:
          type: string
          format: uuid
        assetName:
          type: string
        assetSymbol:
          type: string
        accountManagerId:
          type: string
          format: uuid
        accountManagerName:
          type: string
    iDomainEvent:
      type: object
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT