name: Publish Bicep

on:
  workflow_call:
    inputs:
      main_bicep_file:
        type: string
        required: true
      workflow_environment:
        type: string
        required: true
      parameters:
        type: string
        required: false
    secrets:
      # https://github.com/actions/runner/issues/1490
      # These are actually coming in from the environment, but
      # need to be referenced here due to this bug
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_APIM_NAME:
        required: true
      AZURE_APIM_RG:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ inputs.workflow_environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy API Revisions
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_APIM_RG }}
          template: ${{ inputs.main_bicep_file }}
          parameters: apimServiceName=${{ secrets.AZURE_APIM_NAME }} ${{ inputs.parameters }}

          # NOTE: Parameter JSON files are currently not used. 
          # API configuration's are kept in Github secrets and passed in.
          # parameters: ${{ needs.get_api_folder.outputs.apiFolderPath }}/params.prod.json

          # Example of parameters from: https://github.com/Azure/apim-landing-zone-accelerator/blob/workflow-new/.github/workflows/es-apim.yml
          # parameters: > 
          #   workloadName=${{ fromJson(env.config).RESOURCE_NAME_PREFIX }} environment=${{ fromJson(env.config).ENVIRONMENT_TAG }} 
          #   vmUsername=${{ fromJson(env.config).VM_USERNAME }} vmPassword=${{ secrets.VM_PW }} 
          #   accountName=${{ secrets.ACCOUNT_NAME }} personalAccessToken=${{ secrets.PAT }} CICDAgentType=${{ fromJson(env.config).CICD_AGENT_TYPE}}
          #   appGatewayFqdn=${{ secrets.FQDN }} certificatePassword=${{ secrets.CERTPW }} appGatewayCertType=${{ fromJson(env.config).CERT_TYPE }}

        # Reference: https://github.com/marketplace/actions/azure-login#az-logout-and-security-hardening
      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear