# TODO: parameterize and make re-usable 
name: Publish API Changes to Staging/Prod
on:
  push:
    branches:
      - main
    paths:
      - 'apis/**'
  workflow_dispatch:
    
jobs:
  publish_all_staging:
    name: "Publish API's to Staging"
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy API Revisions
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_APIM_RG }}
          template: apis/main.bicep
          parameters: apimServiceName=${{ secrets.AZURE_APIM_NAME }}

      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear

  publish_all_prod:
    name: "Publish API's to Prod"
    runs-on: ubuntu-latest
    environment: Prod
    needs: publish_api_staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy API Revisions
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_APIM_RG }}
          template: apis/main.bicep
          parameters: apimServiceName=${{ secrets.AZURE_APIM_NAME }}

      - name: Azure logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear