# TODO: parameterize and make re-usable 
name: Publish API Changes to Staging/Prod
on:
  push:
    branches:
      - main
    paths:
      - 'apis/**'
  workflow_dispatch:
    
jobs:
  publish_all_staging:
    name: "Publish API's to Staging"
    uses: ./.github/workflows/publish-api.yml
    with:
      main_bicep_file: apis/main.bicep
      environment: Staging
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_APIM_RG: ${{ secrets.AZURE_APIM_RG }}
      AZURE_APIM_NAME: ${{ secrets.AZURE_APIM_NAME }}

  publish_all_prod:
    name: "Publish API's to Prod"
    uses: ./.github/workflows/publish-api.yml
    needs: publish_all_staging
    with:
      main_bicep_file: apis/main.bicep
      environment: Prod
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_APIM_RG: ${{ secrets.AZURE_APIM_RG }}
      AZURE_APIM_NAME: ${{ secrets.AZURE_APIM_NAME }}