name: Publish API Changes to Staging/Prod
on:
  push:
    branches:
      - main
    paths:
      - 'apis/**'
  workflow_dispatch:
    
jobs:
  validate_bicep:
    name: "Validate Bicep files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: apis

  # Environment doesn't need reviewers, but PR's to `main` do
  publish_all_staging:
    name: "Publish API's to Staging"
    uses: ./.github/workflows/deploy-bicep.yml
    needs: validate_bicep
    with:
      main_bicep_file: apis/main.bicep
      workflow_environment: Staging
    secrets:
      # https://github.com/actions/runner/issues/1490
      # These are actually coming in from the environment, but
      # need to be referenced here due to this bug
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_APIM_RG: ${{ secrets.AZURE_APIM_RG }}
      AZURE_APIM_NAME: ${{ secrets.AZURE_APIM_NAME }}

  # Requires reviewers for Environment
  publish_all_prod:
    name: "Publish API's to Prod"
    uses: ./.github/workflows/deploy-bicep.yml
    needs: publish_all_staging
    with:
      main_bicep_file: apis/main.bicep
      workflow_environment: Prod
    secrets:
      # https://github.com/actions/runner/issues/1490
      # These are actually coming in from the environment, but
      # need to be referenced here due to this bug
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_APIM_RG: ${{ secrets.AZURE_APIM_RG }}
      AZURE_APIM_NAME: ${{ secrets.AZURE_APIM_NAME }}